standard_names:
  time: "time"
  target: "target"

datasets:
  creditcard:
    raw_path: "data/raw/creditcard/creditcard.csv"
    column_mapping:
      Time: "time"
      Class: "target"
    id_column: null

  ieee_cis:
    raw_path: "data/raw/ieee_cis_fraud/train_transaction.csv"
    identity_path: "data/raw/ieee_cis_fraud/train_identity.csv"
    column_mapping:
      TransactionID: "id"
      TransactionDT: "time"
      isFraud: "target"
    id_column: "TransactionID"

standard_columns:
  - "id"
  - "time"
  - "target"
