xgboost:
  n_estimators: 1000
  max_depth: 6
  learning_rate: 0.05
  subsample: 0.8
  colsample_bytree: 0.8
  tree_method: "hist"
  random_state: 42
  n_jobs: -1
  scale_pos_weight: 100 # Tăng trọng số cho lớp gian lận (thiểu số)
  max_delta_step: 1  

lightgbm:
  n_estimators: 1000
  num_leaves: 31
  learning_rate: 0.05
  feature_fraction: 0.8
  bagging_fraction: 0.8
  random_state: 42
  n_jobs: -1
  force_col_wise: true
  verbose: -1          # Ẩn các cảnh báo log
  min_child_samples: 5 # Cho phép chia nhánh với ít mẫu hơn (giúp học tốt hơn trên data nhỏ)
  min_data_per_group: 100
  max_cat_threshold: 32


catboost:
  iterations: 1000
  depth: 6
  learning_rate: 0.05
  random_seed: 42
  logging_level: "Silent"
  allow_writing_files: false
