pipeline:
  mode: "subsample" # Options: "subsample" for testing, "full" for complete dataset
  init_train_size: 1000 # Number of initial samples to bootstrap the model
  subsample_size: 10000 # Number of records to use when mode is 'subsample'

addm:
  hoeffding_delta: 0.01
  min_window_size: 30
  entropy_threshold: 0.99

periodic:
  retrain_interval: 1000 # Number of transactions before retraining

