pipeline:
  mode: "subsample" # Options: "subsample" for testing, "full" for complete dataset
  init_train_size: 1000 # Number of initial samples to bootstrap the model
  subsample_size: 50000 # Number of records to use when mode is 'subsample'

addm:
  hoeffding_delta: 0.01
  min_window_size: 30
  entropy_threshold: 0.99

periodic:
  retrain_interval: 1000 # Long-term full retrain interval

incremental:
  update_interval: 100  # Number of samples before incremental update
  update_trees: 500       # Number of new trees to add per update

hybrid:
  short_term_method: "addm" # Options: "addm", "incremental"
  similarity_threshold: 0.1  # Threshold for direct model selection
  k_neighbors: 3             # Number of neighbors for weighted ensemble


